site_name: Adamanteyes Notiz
site_url: https://adamanteye.github.io/notiz/
site_description: Adamanteye 的笔记仓库
repo_url: https://github.com/adamanteye/notiz

nav:
  - 简介: index.md
  - 计算机网络:
    - Introduction: computer-networks/intro.md
  - Optics:
    - Fabry-Perot Interferometer: optics/fabry-perot-interferometer.md
    - Coherent Theory: optics/coherent-theory.md
    - Diffraction: optics/diffraction.md
  - 基础物理实验:
    - 绪论: physics-lab/intro.md
    - matlab 数据处理: physics-lab/matlab.md
    - 完整实验报告 latex 模板: physics-lab/report-template.md
  - 德语:
    - 名词，冠词和代词: deutsch/nomen-artikel-pronomen.md
    - 形容词: deutsch/adj.md
    - 从句: deutsch/nebensatz.md
    - 地点介词: deutsch/präp.md
    - 时态: deutsch/tempus.md
    - 数词: deutsch/numerale.md
    - 动词: deutsch/verben.md
    - 被动态: deutsch/passiv.md
    - 语篇阅读翻译: deutsch/lese-und-übersätzübung.md
  - 写作与沟通:
    - 高效沟通: writing/communication.md
    - 文献综述: writing/literature-review.md
    - 利用图书馆: writing/libarian.md
  - 计算机图形学:
    - OpenGL 入门: graphics/opengl-tutorial.md
  - 人文社科:
    - 中国近现代史纲要: social-sci/modern-history.md
  - ROS:
    - 小车导航: ros/navigation.md

theme:
  language: zh
  name: material
  font:
    text: 'Noto Serif'
    code: 'Fira Mono'
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: 切换到夜间模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到日间模式

  icon:
    repo: fontawesome/brands/github

  plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition # !!! 格式支持
  - pymdownx.arithmatex: # latex 公式支持
      generic: true
  - pymdownx.highlight:
      linenums: true # 显示代码块行号
  - pymdownx.details # 折叠格式 ???
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {percent_encode: True}}
